### PR TITLE
Add Img students

### PR DESCRIPTION
**Pull request by amryarios**
Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

### CODE REVIEW

**Comment by arjunpandey2003** [comment]
@amryarios is the image size is 240x240
Plus you have to update student.yml

**Comment by amryarios** [comment]
Img that img size is 240 x 240

**Comment by arjunpandey2003** [comment]
you havent updated student.yml

**Comment by amryarios** [comment]
alright https://github.com/amryarios/gci17.fossasia.org/pull/2/commits/449a84091620b0c2e84b845d83c5b3838bcf0805 ?

**Comment by arjunpandey2003** [comment]
Yes commit into the pull request

**Pull request merged**
